package com.maplr.testhockeygame.entity;

import java.io.Serializable;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name="TEAM")
public class TeamEntity implements Serializable {

	/**
	 * Serial version UID autogenerated
	 */
	private static final long serialVersionUID = 3812115560555358955L;

	/**
	 * Id team
	 */
	@Id
	@Column(name="ID_TEAM", nullable=false)
	private long idTeam;
	
	/**
	 * Coach
	 */
	@Column(name="COACH", nullable=false)
	private String coach;
	
	/**
	 * year
	 */
	@Column(name="YEAR_TEAM", nullable=false)
	private long year;
	
	/**
	 * Players of the team
	 */
	
	@OneToMany(mappedBy="teamPlayer", fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
	private List<PlayerEntity> players;

	public long getIdTeam() {
		return idTeam;
	}

	public void setIdTeam(long idTeam) {
		this.idTeam = idTeam;
	}

	public String getCoach() {
		return coach;
	}

	public void setCoach(String coach) {
		this.coach = coach;
	}

	public long getYear() {
		return year;
	}

	public void setYear(long year) {
		this.year = year;
	}

	public List<PlayerEntity> getPlayers() {
		return players;
	}

	public void setPlayers(List<PlayerEntity> players) {
		this.players = players;
	}



	
}
